import { defineArrayMember, defineField, defineType } from "sanity";

export const seo = defineType({
  name: "seo",
  title: "SEO",
  type: "object",
  fields: [
    defineField({
      name: "metaTitle",
      title: "Meta title",
      type: "string",
      validation: (Rule) =>
        Rule.max(60).warning("Keep meta titles around 50-60 characters."),
    }),
    defineField({
      name: "metaDescription",
      title: "Meta description",
      type: "text",
      rows: 3,
      validation: (Rule) =>
        Rule.max(160).warning("Keep meta descriptions around 150-160 characters."),
    }),
    defineField({
      name: "keywords",
      title: "Keywords",
      type: "array",
      of: [defineArrayMember({ type: "string" })],
    }),
    defineField({ name: "canonicalUrl", title: "Canonical URL", type: "url" }),
    defineField({
      name: "noIndex",
      title: "Noindex",
      type: "boolean",
      description: "Ask search engines not to index this page.",
      initialValue: false,
    }),
    defineField({
      name: "excludeFromSitemap",
      title: "Exclude from sitemap",
      type: "boolean",
      initialValue: false,
    }),
    defineField({ name: "ogTitle", title: "Open Graph title", type: "string" }),
    defineField({
      name: "ogDescription",
      title: "Open Graph description",
      type: "text",
      rows: 3,
    }),
    defineField({ name: "ogUrl", title: "Open Graph URL", type: "url" }),
    defineField({
      name: "ogImage",
      title: "Open Graph image",
      type: "image",
      options: { hotspot: true },
      fields: [
        defineField({
          name: "alt",
          type: "string",
          validation: (Rule) => Rule.required().warning("Add alt text for SEO and accessibility."),
        }),
      ],
    }),
    defineField({
      name: "schemaPreset",
      title: "Schema preset",
      type: "string",
      options: {
        list: [
          { title: "None", value: "none" },
          { title: "Organization", value: "Organization" },
          { title: "Article", value: "Article" },
          { title: "Product", value: "Product" },
          { title: "FAQ", value: "FAQPage" },
          { title: "Breadcrumb", value: "BreadcrumbList" },
          { title: "Job posting", value: "JobPosting" },
        ],
      },
      initialValue: "none",
    }),
    defineField({
      name: "schemaJson",
      title: "Schema JSON-LD",
      type: "text",
      rows: 8,
      description:
        "Optional override. If blank, the selected schema preset can be generated by the frontend later.",
      validation: (Rule) =>
        Rule.custom((value) => {
          if (!value) {
            return true;
          }
          try {
            JSON.parse(value);
            return true;
          } catch {
            return "Schema must be valid JSON.";
          }
        }),
    }),
  ],
});

export const link = defineType({
  name: "link",
  title: "Link",
  type: "object",
  fields: [
    defineField({ name: "label", type: "string", validation: (Rule) => Rule.required() }),
    defineField({ name: "href", type: "string", validation: (Rule) => Rule.required() }),
    defineField({
      name: "style",
      type: "string",
      options: {
        list: [
          { title: "Primary", value: "primary" },
          { title: "Secondary", value: "secondary" },
        ],
      },
      initialValue: "primary",
    }),
  ],
});

const richText = defineField({
  name: "body",
  title: "Body",
  type: "array",
  of: [
    defineArrayMember({
      type: "block",
      styles: [
        { title: "Normal", value: "normal" },
        { title: "Heading 2", value: "h2" },
        { title: "Heading 3", value: "h3" },
        { title: "Quote", value: "blockquote" },
      ],
      lists: [
        { title: "Bullet", value: "bullet" },
        { title: "Number", value: "number" },
      ],
      marks: {
        annotations: [
          defineArrayMember({
            name: "link",
            type: "object",
            fields: [defineField({ name: "href", type: "string" })],
          }),
        ],
      },
    }),
  ],
});

const imageField = defineField({
  name: "image",
  type: "image",
  options: { hotspot: true },
  fields: [
    defineField({
      name: "alt",
      type: "string",
      validation: (Rule) => Rule.required().warning("Add alt text for SEO and accessibility."),
    }),
  ],
});

const sectionItem = defineArrayMember({
  name: "sectionItem",
  title: "Section item",
  type: "object",
  fields: [
    defineField({ name: "title", type: "string" }),
    defineField({ name: "value", type: "string" }),
    defineField({ name: "text", type: "text", rows: 3 }),
    defineField({ name: "href", type: "string" }),
    imageField,
  ],
  preview: {
    select: { title: "title", subtitle: "text" },
  },
});

const baseSectionFields = [
  defineField({ name: "eyebrow", type: "string" }),
  defineField({ name: "title", type: "string" }),
  defineField({ name: "subtitle", type: "text", rows: 3 }),
] as const;

export const heroSection = defineType({
  name: "heroSection",
  title: "Hero",
  type: "object",
  fields: [
    ...baseSectionFields,
    richText,
    imageField,
    defineField({ name: "videoUrl", title: "Video URL", type: "url" }),
    defineField({
      name: "ctas",
      title: "Buttons",
      type: "array",
      of: [{ type: "link" }, { type: "reference", to: [{ type: "reusableCta" }] }],
    }),
  ],
  preview: { select: { title: "title", subtitle: "eyebrow" } },
});

export const richTextSection = defineType({
  name: "richTextSection",
  title: "Rich text",
  type: "object",
  fields: [
    ...baseSectionFields,
    richText,
    defineField({
      name: "alignment",
      type: "string",
      options: {
        list: [
          { title: "Left", value: "left" },
          { title: "Center", value: "center" },
        ],
      },
      initialValue: "left",
    }),
  ],
});

export const statsSection = defineType({
  name: "statsSection",
  title: "Stats",
  type: "object",
  fields: [
    ...baseSectionFields,
    defineField({ name: "items", type: "array", of: [sectionItem] }),
  ],
});

export const cardGridSection = defineType({
  name: "cardGridSection",
  title: "Card grid",
  type: "object",
  fields: [
    ...baseSectionFields,
    defineField({ name: "items", type: "array", of: [sectionItem] }),
  ],
});

export const mediaSection = defineType({
  name: "mediaSection",
  title: "Media",
  type: "object",
  fields: [
    ...baseSectionFields,
    richText,
    imageField,
    defineField({ name: "videoUrl", title: "Video URL", type: "url" }),
    defineField({
      name: "ctas",
      title: "Buttons",
      type: "array",
      of: [{ type: "link" }, { type: "reference", to: [{ type: "reusableCta" }] }],
    }),
  ],
});

export const carouselSection = defineType({
  name: "carouselSection",
  title: "Carousel",
  type: "object",
  fields: [
    ...baseSectionFields,
    defineField({ name: "items", type: "array", of: [sectionItem] }),
  ],
});

export const logoCloudSection = defineType({
  name: "logoCloudSection",
  title: "Logo cloud",
  type: "object",
  fields: [
    ...baseSectionFields,
    defineField({ name: "items", type: "array", of: [sectionItem] }),
  ],
});

export const featureTabsSection = defineType({
  name: "featureTabsSection",
  title: "Feature tabs",
  type: "object",
  fields: [
    ...baseSectionFields,
    defineField({ name: "items", type: "array", of: [sectionItem] }),
  ],
});

export const ctaSection = defineType({
  name: "ctaSection",
  title: "CTA",
  type: "object",
  fields: [
    ...baseSectionFields,
    defineField({
      name: "ctas",
      title: "Buttons",
      type: "array",
      of: [{ type: "link" }, { type: "reference", to: [{ type: "reusableCta" }] }],
    }),
  ],
});

export const formSection = defineType({
  name: "formSection",
  title: "Form",
  type: "object",
  fields: [
    ...baseSectionFields,
    defineField({
      name: "formRef",
      title: "Reusable HubSpot form",
      type: "reference",
      to: [{ type: "hubspotForm" }],
      description: "Preferred for production forms. Inline form below remains available for beta/testing.",
    }),
    defineField({
      name: "form",
      type: "object",
      fields: [
        defineField({
          name: "provider",
          type: "string",
          options: {
            list: [
              { title: "Native beta form", value: "native" },
              { title: "HubSpot embed", value: "hubspot" },
            ],
          },
          initialValue: "native",
        }),
        defineField({ name: "title", type: "string" }),
        defineField({ name: "description", type: "text", rows: 3 }),
        defineField({ name: "hubspotPortalId", title: "HubSpot portal ID", type: "string" }),
        defineField({ name: "hubspotFormId", title: "HubSpot form ID", type: "string" }),
        defineField({
          name: "fields",
          type: "array",
          of: [
            defineArrayMember({
              type: "object",
              fields: [
                defineField({ name: "label", type: "string" }),
                defineField({ name: "name", type: "string" }),
                defineField({
                  name: "type",
                  type: "string",
                  options: {
                    list: ["text", "email", "tel", "textarea"],
                  },
                  initialValue: "text",
                }),
                defineField({ name: "required", type: "boolean", initialValue: false }),
              ],
            }),
          ],
        }),
      ],
    }),
  ],
});

export const downloadSection = defineType({
  name: "downloadSection",
  title: "Download",
  type: "object",
  fields: [
    ...baseSectionFields,
    defineField({
      name: "resource",
      title: "Resource",
      type: "reference",
      to: [{ type: "resource" }],
      description: "Preferred for reusable whitepapers, PDFs, brochures, and gated assets.",
    }),
    defineField({
      name: "download",
      type: "object",
      fields: [
        defineField({ name: "title", type: "string" }),
        defineField({ name: "description", type: "text", rows: 3 }),
        defineField({ name: "file", type: "file" }),
      ],
    }),
  ],
});

export const faqSection = defineType({
  name: "faqSection",
  title: "FAQ",
  type: "object",
  fields: [
    ...baseSectionFields,
    defineField({
      name: "items",
      type: "array",
      of: [
        defineArrayMember({
          type: "object",
          fields: [
            defineField({ name: "question", type: "string", validation: (Rule) => Rule.required() }),
            defineField({ name: "answer", type: "text", rows: 4, validation: (Rule) => Rule.required() }),
          ],
          preview: { select: { title: "question", subtitle: "answer" } },
        }),
      ],
    }),
  ],
});

export const testimonialSection = defineType({
  name: "testimonialSection",
  title: "Testimonials",
  type: "object",
  fields: [
    ...baseSectionFields,
    defineField({
      name: "items",
      type: "array",
      of: [
        defineArrayMember({
          type: "object",
          fields: [
            defineField({ name: "quote", type: "text", rows: 4, validation: (Rule) => Rule.required() }),
            defineField({ name: "person", type: "string" }),
            defineField({ name: "role", type: "string" }),
            defineField({ name: "company", type: "string" }),
            imageField,
          ],
          preview: { select: { title: "person", subtitle: "company" } },
        }),
      ],
    }),
  ],
});

export const sections = [
  heroSection,
  richTextSection,
  statsSection,
  cardGridSection,
  mediaSection,
  carouselSection,
  logoCloudSection,
  featureTabsSection,
  ctaSection,
  formSection,
  downloadSection,
  faqSection,
  testimonialSection,
];
